// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "VAzadi_top_verilator__Syms.h"
#include "VAzadi_top_verilator.h"
#include "VAzadi_top_verilator___024unit.h"
#include "VAzadi_top_verilator_tlul_socket_m1__pi7.h"
#include "VAzadi_top_verilator_gpio_reg_pkg.h"
#include "VAzadi_top_verilator_rv_plic_reg_pkg.h"
#include "VAzadi_top_verilator_uart_reg_pkg.h"
<<<<<<< HEAD
=======
#include "VAzadi_top_verilator_i2c_reg_pkg.h"
>>>>>>> 8883d9b324c489ad01ca11f681acb89fb7eab79d
#include "VAzadi_top_verilator_rv_timer_reg_pkg.h"
#include "VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15.h"



// FUNCTIONS
VAzadi_top_verilator__Syms::VAzadi_top_verilator__Syms(VAzadi_top_verilator* topp, const char* namep)
    // Setup locals
    : __Vm_namep(namep)
    , __Vm_activity(false)
    , __Vm_baseCode(0)
    , __Vm_didInit(false)
    // Setup submodule names
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.DCCM"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.DCCM.gen_host_fifo[0].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.DCCM.gen_host_fifo[1].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.DEBUG_ROM"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.DEBUG_ROM.gen_host_fifo[0].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.DEBUG_ROM.gen_host_fifo[1].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.FLASH_CTRL.gen_host_fifo[0].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.FLASH_CTRL.gen_host_fifo[1].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.FLASH_CTRL.gen_host_fifo[2].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.ICCM.gen_host_fifo[0].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.ICCM.gen_host_fifo[1].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.ICCM.gen_host_fifo[2].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.PLIC"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.PLIC.gen_host_fifo[0].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.PLIC.gen_host_fifo[1].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_0"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_0.gen_host_fifo[0].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_0.gen_host_fifo[1].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_1"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_1.gen_host_fifo[0].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_1.gen_host_fifo[1].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_2"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_2.gen_host_fifo[0].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_2.gen_host_fifo[1].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_3"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_3.gen_host_fifo[0].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_3.gen_host_fifo[1].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_4"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_4.gen_host_fifo[0].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.TIMER_4.gen_host_fifo[1].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.XBAR_PERI"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.XBAR_PERI.gen_host_fifo[0].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.XBAR_PERI.gen_host_fifo[1].u_hostfifo"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_1.gen_dfifo[0].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_1.gen_dfifo[1].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_1.gen_dfifo[2].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_2.gen_dfifo[0].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_2.gen_dfifo[10].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_2.gen_dfifo[1].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_2.gen_dfifo[2].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_2.gen_dfifo[3].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_2.gen_dfifo[4].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_2.gen_dfifo[5].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_2.gen_dfifo[6].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_2.gen_dfifo[7].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_2.gen_dfifo[8].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_2.gen_dfifo[9].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_3.gen_dfifo[0].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_3.gen_dfifo[1].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_3.gen_dfifo[2].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_3.gen_dfifo[3].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_3.gen_dfifo[4].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_3.gen_dfifo[5].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_3.gen_dfifo[6].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_3.gen_dfifo[7].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_3.gen_dfifo[8].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.main_swith.host_3.gen_dfifo[9].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[0].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[10].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__11__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[11].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__12__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[12].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[1].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[2].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[3].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[4].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[5].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[6].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[7].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[8].fifo_d"))
    , TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d(Verilated::catName(topp->name(), "Azadi_top_verilator.top_verilator.periph_switch.u_s1n_14.gen_dfifo[9].fifo_d"))
    , TOP__gpio_reg_pkg(Verilated::catName(topp->name(), "gpio_reg_pkg"))
<<<<<<< HEAD
=======
    , TOP__i2c_reg_pkg(Verilated::catName(topp->name(), "i2c_reg_pkg"))
>>>>>>> 8883d9b324c489ad01ca11f681acb89fb7eab79d
    , TOP__rv_plic_reg_pkg(Verilated::catName(topp->name(), "rv_plic_reg_pkg"))
    , TOP__rv_timer_reg_pkg(Verilated::catName(topp->name(), "rv_timer_reg_pkg"))
    , TOP__uart_reg_pkg(Verilated::catName(topp->name(), "uart_reg_pkg"))
{
    // Pointer to top level
    TOPp = topp;
    // Setup each module's pointers to their submodules
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM->__PVT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM->__PVT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM->__PVT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM->__PVT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC->__PVT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC->__PVT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0 = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0->__PVT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0->__PVT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1 = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1->__PVT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1->__PVT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2 = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2->__PVT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2->__PVT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3 = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3->__PVT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3->__PVT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4 = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4->__PVT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4->__PVT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI->__PVT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI->__PVT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__11__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__11__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__12__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__12__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d;
    TOPp->__PVT__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d = &TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d;
    TOPp->__PVT__gpio_reg_pkg = &TOP__gpio_reg_pkg;
<<<<<<< HEAD
=======
    TOPp->__PVT__i2c_reg_pkg = &TOP__i2c_reg_pkg;
>>>>>>> 8883d9b324c489ad01ca11f681acb89fb7eab79d
    TOPp->__PVT__rv_plic_reg_pkg = &TOP__rv_plic_reg_pkg;
    TOPp->__PVT__rv_timer_reg_pkg = &TOP__rv_timer_reg_pkg;
    TOPp->__PVT__uart_reg_pkg = &TOP__uart_reg_pkg;
    // Setup each module's pointer back to symbol table (for public functions)
    TOPp->__Vconfigure(this, true);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM.__Vconfigure(this, true);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo.__Vconfigure(this, true);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__11__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__12__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d.__Vconfigure(this, false);
    TOP__gpio_reg_pkg.__Vconfigure(this, true);
<<<<<<< HEAD
=======
    TOP__i2c_reg_pkg.__Vconfigure(this, true);
>>>>>>> 8883d9b324c489ad01ca11f681acb89fb7eab79d
    TOP__rv_plic_reg_pkg.__Vconfigure(this, true);
    TOP__rv_timer_reg_pkg.__Vconfigure(this, true);
    TOP__uart_reg_pkg.__Vconfigure(this, true);
    // Setup export functions
    for (int __Vfinal=0; __Vfinal<2; __Vfinal++) {
    }
}
