// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef _VAZADI_TOP_VERILATOR__SYMS_H_
#define _VAZADI_TOP_VERILATOR__SYMS_H_  // guard

#include "verilated_heavy.h"

// INCLUDE MODULE CLASSES
#include "VAzadi_top_verilator.h"
#include "VAzadi_top_verilator___024unit.h"
#include "VAzadi_top_verilator_tlul_socket_m1__pi7.h"
#include "VAzadi_top_verilator_gpio_reg_pkg.h"
#include "VAzadi_top_verilator_rv_plic_reg_pkg.h"
#include "VAzadi_top_verilator_uart_reg_pkg.h"
<<<<<<< HEAD
=======
#include "VAzadi_top_verilator_i2c_reg_pkg.h"
>>>>>>> 8883d9b324c489ad01ca11f681acb89fb7eab79d
#include "VAzadi_top_verilator_rv_timer_reg_pkg.h"
#include "VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS
class VAzadi_top_verilator__Syms : public VerilatedSyms {
  public:
    
    // LOCAL STATE
    const char* __Vm_namep;
    bool __Vm_activity;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode;  ///< Used by trace routines when tracing multiple models
    bool __Vm_didInit;
    
    // SUBCELL STATE
    VAzadi_top_verilator*          TOPp;
    VAzadi_top_verilator_tlul_socket_m1__pi7 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DCCM__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_socket_m1__pi7 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__DEBUG_ROM__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__FLASH_CTRL__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__ICCM__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_socket_m1__pi7 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__PLIC__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_socket_m1__pi7 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_0__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_socket_m1__pi7 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_1__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_socket_m1__pi7 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_2__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_socket_m1__pi7 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_3__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_socket_m1__pi7 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__TIMER_4__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_socket_m1__pi7 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__XBAR_PERI__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_1__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_2__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__main_swith__DOT__host_3__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__11__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__12__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d;
    VAzadi_top_verilator_tlul_fifo_sync__RCz15_RDz15 TOP__Azadi_top_verilator__DOT__top_verilator__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d;
    VAzadi_top_verilator_gpio_reg_pkg TOP__gpio_reg_pkg;
<<<<<<< HEAD
=======
    VAzadi_top_verilator_i2c_reg_pkg TOP__i2c_reg_pkg;
>>>>>>> 8883d9b324c489ad01ca11f681acb89fb7eab79d
    VAzadi_top_verilator_rv_plic_reg_pkg TOP__rv_plic_reg_pkg;
    VAzadi_top_verilator_rv_timer_reg_pkg TOP__rv_timer_reg_pkg;
    VAzadi_top_verilator_uart_reg_pkg TOP__uart_reg_pkg;
    
    // CREATORS
    VAzadi_top_verilator__Syms(VAzadi_top_verilator* topp, const char* namep);
    ~VAzadi_top_verilator__Syms() = default;
    
    // METHODS
    inline const char* name() { return __Vm_namep; }
    
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

#endif  // guard
