// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vazadi_soc_top.h for the primary calling header

#ifndef _VAZADI_SOC_TOP_TLUL_FIFO_SYNC__RCZ1_RDZ1_H_
#define _VAZADI_SOC_TOP_TLUL_FIFO_SYNC__RCZ1_RDZ1_H_  // guard

#include "verilated_heavy.h"

//==========

class Vazadi_soc_top__Syms;
class Vazadi_soc_top_VerilatedVcd;


//----------

VL_MODULE(Vazadi_soc_top_tlul_fifo_sync__RCz1_RDz1) {
  public:
    
    // PORTS
    VL_IN8(clk_i,0,0);
    VL_IN8(rst_ni,0,0);
    VL_IN8(spare_req_i,0,0);
    VL_OUT8(__PVT__spare_req_o,0,0);
    VL_IN8(spare_rsp_i,0,0);
    VL_OUT8(__PVT__spare_rsp_o,0,0);
    VL_INW(tl_h_i,85,0,3);
    VL_OUT64(tl_h_o,51,0);
    VL_OUTW(tl_d_o,85,0,3);
    VL_IN64(tl_d_i,51,0);
    
    // INTERNAL VARIABLES
  private:
    Vazadi_soc_top__Syms* __VlSymsp;  // Symbol table
  public:
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vazadi_soc_top_tlul_fifo_sync__RCz1_RDz1);  ///< Copying not allowed
  public:
    Vazadi_soc_top_tlul_fifo_sync__RCz1_RDz1(const char* name = "TOP");
    ~Vazadi_soc_top_tlul_fifo_sync__RCz1_RDz1();
    
    // INTERNAL METHODS
    void __Vconfigure(Vazadi_soc_top__Syms* symsp, bool first);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_14__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d__45(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_14__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d__86(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_14__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d__46(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_14__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d__87(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_14__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d__47(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_14__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d__88(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d__36(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d__89(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d__37(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d__90(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d__38(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d__91(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d__39(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d__92(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d__40(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d__93(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d__41(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d__94(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d__42(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d__95(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d__43(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d__96(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d__44(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_18__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d__97(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d__14(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d__98(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d__15(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d__99(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d__100(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d__16(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d__101(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d__17(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d__102(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d__18(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d__103(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d__19(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d__104(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d__20(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d__105(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d__21(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d__106(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_s1n_35__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d__22(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_16__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__48(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_16__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__67(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_16__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__49(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_16__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__68(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_16__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo__50(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_16__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo__69(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_19__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__65(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_19__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__84(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_19__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__66(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_19__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__85(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_21__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__51(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_21__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__70(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_21__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__52(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_21__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__71(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_23__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__53(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_23__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__72(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_23__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__54(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_23__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__73(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_25__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__55(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_25__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__74(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_25__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__56(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_25__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__75(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_27__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__57(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_27__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__76(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_27__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__58(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_27__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__77(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_29__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__59(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_29__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__78(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_29__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__60(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_29__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__79(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_31__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__61(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_31__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__80(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_31__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__62(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_31__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__81(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_33__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__63(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_33__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo__82(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_33__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__64(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__main_swith__DOT__u_sm1_33__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo__83(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d__1(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d__23(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d__11(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__10__KET____DOT__fifo_d__33(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__11__KET____DOT__fifo_d__12(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__11__KET____DOT__fifo_d__34(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__12__KET____DOT__fifo_d__13(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__12__KET____DOT__fifo_d__35(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d__2(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d__24(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d__25(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d__3(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d__26(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d__4(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d__27(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__4__KET____DOT__fifo_d__5(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d__28(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__5__KET____DOT__fifo_d__6(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d__29(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__6__KET____DOT__fifo_d__7(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d__30(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__7__KET____DOT__fifo_d__8(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d__31(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__8__KET____DOT__fifo_d__9(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d__10(Vazadi_soc_top__Syms* __restrict vlSymsp);
    void _settle__TOP__azadi_soc_top__DOT__periph_switch__DOT__u_s1n_14__DOT__gen_dfifo__BRA__9__KET____DOT__fifo_d__32(Vazadi_soc_top__Syms* __restrict vlSymsp);
  private:
    static void traceInit(void* userp, VerilatedVcd* tracep, uint32_t code) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
