# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.cache/wt} [current_project]
set_property parent.project_path {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/dummy_memory/DFFRAM.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/dummy_memory/DFFRAMD.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/tlul_pkg.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_pkg.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_core.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/azadi_soc/rtl/brq_core_top.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_counter.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_cs_registers.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_csr.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_exu.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_exu_alu.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_exu_multdiv_fast.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_exu_multdiv_slow.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_idu.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_idu_controller.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_idu_decoder.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_ifu.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_ifu_compressed_decoder.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_ifu_dummy_instr.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_ifu_fifo.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_ifu_icache.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_ifu_prefetch_buffer.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_lsu.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_pmp.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_register_file_ff.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/brq_core/rtl/brq_wbu.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/dummy_memory/data_mem.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/fifo_sync.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/GPIO/rtl/gpio_reg_pkg.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/GPIO/rtl/gpio.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/GPIO/rtl/gpio_reg_top.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/dummy_memory/instr_mem_top.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/primitives/rtl/prim_arbiter_ppc.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/buraq_core/prim_pkg.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/primitives/rtl/prim_clock_gating.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/primitives/rtl/prim_filter_ctr.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/primitives/rtl/prim_generic_clock_gating.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/primitives/rtl/prim_intr_hw.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/primitives/rtl/prim_subreg.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/primitives/rtl/prim_subreg_arb.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/primitives/rtl/prim_subreg_ext.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/tl_main_pkg.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/tl_periph_pkg.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/tlul_adapter_reg.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/tlul_err.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/tlul_err_resp.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/tlul_fifo_sync.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/tlul_host_adapter.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/tlul_socket_1n.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/tlul_socket_m1.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/tlul_sram_adapter.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/xbar_mai_t.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/TileLink/rtl/xbar_periph.sv}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/imports/src/azadi_soc/rtl/azadi_soc_top.sv}
}
read_verilog -library xil_defaultlib {
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/new/iccm_controller.v}
  {/home/merl-lab/Documents/Vivado Projects/azadi/azadi.srcs/sources_1/new/uart_rx.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top azadi_soc_top -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef azadi_soc_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file azadi_soc_top_utilization_synth.rpt -pb azadi_soc_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
